- name: Install prerequisites
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - postgresql-client
    - curl
    - virtualenv

- name: Clone QGIS-Server-PerfSuite
  git:
    repo: https://github.com/oslandia/QGIS-Server-PerfSuite
    dest: "/home/{{ user }}/{{ prefix }}/QGIS-Server-PerfSuite"
  become_user: "{{ user }}"

- name: Copy ci script
  copy:
    dest: "/home/{{ user }}/{{ prefix }}/perfsuite-ci.sh"
    src: "perfsuite-ci.sh"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Update crontab to periodically run performance tests
  cron:
    name: perfsuite ci
    user: "{{ user }}"
    minute: "0"
    hour: "{{ perfsuite_hour }}"
    job: >
      cd /home/{{ user }}/{{ prefix }} && sh perfsuite-ci.sh > /tmp/perfsuite-ci.log 2>&1
