- name: Install prerequisites
  apt:
    name: ['postgresql-client', 'curl', 'virtualenv']
    update_cache: yes

- name: Copy aggregate report scripts
  copy:
    dest: "/home/{{ user }}/{{ prefix }}/"
    src: "{{ playbook_dir }}/../perfsuite-aggregate"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Clone QGIS-Server-PerfSuite
  git:
    repo: https://github.com/oslandia/QGIS-Server-PerfSuite
    dest: "/home/{{ user }}/{{ prefix }}/QGIS-Server-PerfSuite"
  become_user: "{{ user }}"

- name: Copy ci script
  copy:
    dest: "/home/{{ user }}/{{ prefix }}/perfsuite-ci.sh"
    src: "perfsuite-ci.sh"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Update crontab to periodically run performance tests
  cron:
    name: perfsuite ci
    user: "{{ user }}"
    minute: "0"
    hour: "{{ perfsuite_hour }}"
    job: >
      cd /home/{{ user }}/{{ prefix }} && sh perfsuite-ci.sh > /tmp/perfsuite-ci.log 2>&1

- name: Update crontab to periodically build aggregate performance report
  cron:
    name: perfsuite aggregate report ci
    user: "{{ user }}"
    minute: "0"
    hour: "{{ perfsuite_aggregate_hour }}"
    job: >
      cd /home/{{ user }}/{{ prefix }}/perfsuite-aggregate/ && sh aggregate-ci.sh > /tmp/perfsuite-aggregate-ci.log 2>&1
