- name: Install prerequisites
  apt:
    name: ['xmlstarlet']
    update_cache: yes

- name: Clone QGIS-Server-CertifSuite
  git:
    repo: https://github.com/qgis/QGIS-Server-CertifSuite
    dest: "/home/{{ user }}/QGIS-Server-CertifSuite"
  register: git_repo_certifsuite

- name: Change owner and group of QGIS-Server-CertifSuite
  file:
    dest: "/home/{{ user }}/QGIS-Server-CertifSuite"
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: True
  when: git_repo_certifsuite.changed

- name: Copy ci script
  template:
    dest: "/home/{{ user }}/certifsuite-ci.sh"
    src: "certifsuite-ci.sh"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Update crontab to periodically run ogc tests
  cron:
    name: certifsuite ci
    user: "{{ user }}"
    minute: "0"
    hour: "{{ certifsuite_hour }}"
    job: >
      cd /home/{{ user }} && sh certifsuite-ci.sh > /tmp/certifsuite-ci.log 2>&1
