- name: Install prerequisites
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - xmlstarlet

- name: Clone QGIS-Server-CertifSuite
  git:
    repo: https://github.com/oslandia/QGIS-Server-CertifSuite
    dest: "/home/{{ user }}/{{ prefix }}/QGIS-Server-CertifSuite"
  become_user: "{{ user }}"

- name: Copy ci script
  copy:
    dest: "/home/{{ user }}/{{ prefix }}/certifsuite-ci.sh"
    src: "certifsuite-ci.sh"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Copy certification scripts
  copy:
    dest: "/home/{{ user }}/{{ prefix }}/certification/"
    src: "{{ playbook_dir }}/../certification/"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Update crontab to periodically run ogc tests
  cron:
    name: certifsuite ci
    user: "{{ user }}"
    minute: "0"
    hour: "{{ certifsuite_hour }}"
    job: >
      cd /home/{{ user }}/{{ prefix }}/ && sh certifsuite-ci.sh > /tmp/certifsuite-ci.log 2>&1

- name: Update crontab to periodically run online instances for certification process
  cron:
    name: certification
    user: "{{ user }}"
    minute: "0"
    hour: "{{ certification_hour }}"
    job: >
      cd /home/{{ user }}/{{ prefix }}/certification/ && sh certification.sh > /tmp/certification.log 2>&1

- name: Copy nginx configuration file
  template:
    dest: /etc/nginx/sites-available/certification
    src: certification

- name: Activate certification site
  file: src=/etc/nginx/sites-available/certification
        dest=/etc/nginx/sites-enabled/certification
        state=link

- name: Restart nginx
  service: name=nginx
           state=restarted
